In [ ]:
# The "Data Master" Final Challenge
models_used = ["llama-3", "gpt-4", "llama-3", "gemini", "gpt-4"]
unique_models = set(models_used)
server_config = ("192.168.1.1",8080)

print(server_config[0])
print(unique_models)
try:
    server_config[1] = 433
except Exception as e:
    print(e)




In [ ]:
duplicate_tokens = [10, 20, 10, 30, 20]
cleaned_tokens = list(set(duplicate_tokens))
print(type(cleaned_tokens))
print(cleaned_tokens)

DICTS

In [ ]:
inventory = {'apples': 20, 'bananas': 12, 'oranges': 8}

inventory['apples']= inventory.get('apples') + 5

inventory['pears'] = 15

if not 'grapes' in  inventory.keys() :
    inventory['grapes'] = 0

print(inventory)


In [ ]:
# Challenge 2: The Data Merger

sensors = ['temp_01', 'temp_02', 'humidity_01', 'pressure_01']
readings = [22.5, 23.1, 45.0, 1013.2]
sensor_data = dict(zip(sensors,readings))
        


# sensor_data = {key : value for key in sensors for value in readings}

for key, value in sensor_data.items():
    print(f"Sensor {key} is reposrting {value}")

print((sensor_data))


In [ ]:
# Challenge 3: Dictionary Comprehension
prices_usd = {'laptop': 1200, 'mouse': 25, 'monitor': 200, 'keyboard': 50}

# for key,val in prices_usd.items():
#     print(key,val)

prices_euro ={key : (price * 0.92) for key,price in prices_usd.items() if (price * 0.92) > 100}

print(prices_euro)

In [ ]:
# Challenge 4: The Frequency Counter (The "Boss" Level)
text = "python is fun and python is fast"
word_count= {}
splitted = text.split(" ")
counter = 0
for value in splitted:
    if value in word_count.keys():
        word_count[value] += counter +1
    
    elif not value in word_count.keys():
        word_count[value] = 1
        
print(word_count)







In [ ]:
#Challenge 1: The Email Formatter
user_input = "   john.doe@Example.COM   "
print(user_input.strip().lower())



In [ ]:
# Challenge 2: Secret Code (Slicing)
secret_phrase = "The password is: RedPanda2026"
print(secret_phrase.split(": ")[1])

In [ ]:
# Challenge 3: The URL Builder
protocol = "https"
domain = "google.com"
search_term = "python_tutorials"

print(f"{protocol}://{domain}{search_term}")




In [1]:
# Challenge 1: The Safe Calculator
print("test")

test


In [7]:
# Conditional transforamtion 

numbers = [1,2,3,4,5,6,7,8,9]

computed = [value**2 if value % 2 == 0 else value for value in numbers]
print(computed)

for index, item in enumerate (numbers):
    print(index)

[1, 4, 3, 16, 5, 36, 7, 64, 9]
0
1
2
3
4
5
6
7
8


In [10]:
value = "23.33"
print(value[2:3])

value = ' this is   double   spacing okk  ss   '

value = " ".join(value.split())
print(value)



.
this is double spacing okk ss


In [ ]:
import numpy as np

arr1D = np.array([1,2,3,4,5] )
print(arr1D.shape)
print(arr1D.size)
print(arr1D)


(5,)
5
[1 2 3 4 5]


In [17]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]] )

print(arr2D)
print(arr2D[1,1])
print(arr2D[:,2])
print(arr2D[2,:])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
[3 6 9]
[7 8 9]


In [27]:
arr3D = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1.1,2.2,3.3],[4,5,6],[7,8,9]]])

print(arr3D)
print(arr3D[0,0,1])


[[[1.  2.  3. ]
  [4.  5.  6. ]
  [7.  8.  9. ]]

 [[1.1 2.2 3.3]
  [4.  5.  6. ]
  [7.  8.  9. ]]]
2.0


In [32]:
#Dimension,row,column
arr3d = np.random.rand(3,3,2)
print(arr3d)
print(arr3d[0,1,:])

[[[0.68492768 0.12506963]
  [0.76459886 0.32723788]
  [0.19315386 0.56751659]]

 [[0.38277485 0.73206558]
  [0.90530958 0.9353519 ]
  [0.49792604 0.31334907]]

 [[0.42095461 0.93742007]
  [0.83953003 0.30475852]
  [0.10973159 0.42873882]]]
[0.76459886 0.32723788]


In [ ]:
import pandas as pd